name: Momence Member Cancellation Automation

on:
  schedule:
    # ⚠️ IMPORTANT: GitHub Actions Scheduling Limitations
    # While configured for every 5 minutes, GitHub does NOT guarantee precise scheduling.
    # Actual execution may occur every 1-3 hours due to platform load and limitations.
    # This is a known GitHub Actions limitation documented at:
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
    # 
    # For time-sensitive operations, use the manual workflow_dispatch trigger below.
    # See GITHUB_ACTIONS_SCHEDULE_LIMITATIONS.md for detailed explanation and solutions.
    - cron: '*/5 * * * *'  # Configured interval (actual timing varies)
  
  # Allows manual triggering from GitHub Actions tab
  workflow_dispatch:
    inputs:
      log_level:
        description: 'Log level'
        required: false
        default: 'info'
        type: choice
        options:
        - info
        - debug

# Ensure only one workflow runs at a time
concurrency:
  group: momence-cancellation
  cancel-in-progress: false

jobs:
  cancel-member-bookings:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: 📥 Checkout repository
      uses: actions/checkout@v4
      
    - name: 🟢 Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: 📦 Install dependencies
      run: |
        echo "Installing dependencies..."
        npm ci --production
        echo "Dependencies installed successfully"
        
    - name: 🔍 Validate environment
      run: |
        echo "Validating required secrets..."
        if [ -z "${{ secrets.MOMENCE_ACCESS_TOKEN }}" ]; then
          echo "❌ MOMENCE_ACCESS_TOKEN secret is missing"
          exit 1
        fi
        if [ -z "${{ secrets.MOMENCE_ALL_COOKIES }}" ]; then
          echo "❌ MOMENCE_ALL_COOKIES secret is missing"
          exit 1
        fi
        if [ -z "${{ secrets.GOOGLE_CLIENT_ID }}" ]; then
          echo "❌ GOOGLE_CLIENT_ID secret is missing"
          exit 1
        fi
        if [ -z "${{ secrets.GOOGLE_CLIENT_SECRET }}" ]; then
          echo "❌ GOOGLE_CLIENT_SECRET secret is missing"
          exit 1
        fi
        if [ -z "${{ secrets.GOOGLE_REFRESH_TOKEN }}" ]; then
          echo "❌ GOOGLE_REFRESH_TOKEN secret is missing"
          exit 1
        fi
        if [ -z "${{ secrets.GOOGLE_SHEET_ID }}" ]; then
          echo "⚠️ GOOGLE_SHEET_ID secret is missing - using default"
        else
          echo "✅ GOOGLE_SHEET_ID is configured"
        fi
        echo "✅ All required secrets are present"
        
    - name: 🚀 Run member cancellation process
      id: cancellation
      run: |
        echo "Starting cancellation process at $(date -u)"
        node lc1.js
        echo "Process completed successfully at $(date -u)"
      env:
        MOMENCE_ACCESS_TOKEN: ${{ secrets.MOMENCE_ACCESS_TOKEN }}
        MOMENCE_ALL_COOKIES: ${{ secrets.MOMENCE_ALL_COOKIES }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        GOOGLE_SHEET_ID: ${{ secrets.GOOGLE_SHEET_ID }}
        NODE_ENV: production
        GITHUB_ACTIONS: true
        
    - name: Upload error logs on failure
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: error-logs-${{ github.run_number }}
        path: |
          *.log
          error-*.txt
        retention-days: 30
        
    - name: 💬 Report results
      if: always()
      run: |
        if [ "${{ job.status }}" == "success" ]; then
          echo "✅ Cancellation process completed successfully"
          echo "📊 Check the Google Sheet for detailed results"
        else
          echo "❌ Cancellation process failed"
          echo "📋 Logs have been uploaded as artifacts for debugging"
          echo "🔧 Check the workflow logs for detailed error information"
        fi
        
    - name: 🔔 Notify on critical failure
      if: failure()
      run: |
        echo "🚨 CRITICAL: Momence cancellation workflow failed!"
        echo "Timestamp: $(date -u)"
        echo "Workflow: ${{ github.workflow }}"
        echo "Run ID: ${{ github.run_id }}"
        echo "Please investigate immediately."
        exit 1